### ISSUE TITLE
Find Bugs/Debug

### ISSUE THREAD

**Issue by patrickly** [violangreg/CECS491A#85]
Bugs from this commit: https://github.com/WasteNotCSULB/WebApp/commit/47cb956d3d9125f1b0937f825fbeb47afff82bfc

**Comment by patrickly** [comment]
Bug 1] On the home-page, clicking on these four buttons (Compost, Recycle, Landfill, and Categories) does not work.

**Comment by patrickly** [comment]
Bug 2] Some items display an error message, "Cannot read property 'name' of undefined." Here's a screenshot:
![Screen Shot 2018-10-06 at 8.43.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f56b7191a370f116284f5d5d5ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19141c95df543e94556ad113263e6752431.png)

**Comment by patrickly** [comment]
10.6.18 Time on bug-hunting and debugging: 70 minutes

**Comment by patrickly** [comment]
Run the api server. Go to the server directory and type nodemon.
Then in your browser,  go to: http://localhost:3030/api/bins/
![Screen Shot 2018-10-06 at 8.53.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f56b7191a370f117284f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a29841c95df543e94551a013356bee772431.png)
---
This means that we can get a list of all of the bins.
However, when we want to get a list of all items from a specific bin (http://localhost:3030/api/bins/5ae79d9d027d2834db315428), there is this error, "type is not defined."
---
ReferenceError: type is not defined
    at async.parallel.totalItems (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/routes/main.js:205:9)
    at /Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/async/dist/async.js:1103:5)
    at _parallel (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/async/dist/async.js:3948:5)
    at router.get (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/routes/main.js:184:9)
    at Layer.handle [as handle_request] (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/index.js:281:22
    at param (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/patrickly/Documents/gitkraken/wasteNot/WebApp/server/node_modules/express/lib/router/index.js:275:10)
---
![Screen Shot 2018-10-06 at 8.54.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f56b7191a370f1172f4f5b565ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a29841c95df543e94551a01a3f64ef732431.png)

**Comment by patrickly** [comment]
So from the above error, "ReferenceError: type is not defined
at async.parallel.totalItems," we have a problem on the back-end.

**Comment by patrickly** [comment]
Worked on Bug 1] Can now click on compost, recycle, landfill (CRL). However, the the categories button is still not working. Time: 2 hours. 
Bug 5] However there seems to be fewer items than expected when you click on compost, recycle, landfill.
Bug 6] Refused to apply style from 'http://localhost:4200/styles.scss' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
---
Bug 6 Screenshot]
![Screen Shot 2018-10-07 at 6.04.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f46b7191a37ef1122f4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a29841c95df543e84b55a3113160e3752431.png)
---

**Comment by patrickly** [comment]
Bug 5] Fixed with #87

**Comment by patrickly** [comment]
Bug 7] Search function not working. Backend search api seems to work fine. So it's probably a front-end issue with the search function.

**Comment by patrickly** [comment]
Bug 7 Fixed
